# Generated by Django 3.2.6 on 2022-06-09 11:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('register_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default=1234567890, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(choices=[('is_staff', 'is_staff'), ('is_student', 'is_student'), ('is_admin', 'is_admin')], default='0', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_data_entry', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=30)),
                ('standard', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('section', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=45)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
