# Generated by Django 3.2.5 on 2022-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220607_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('is_student', 'is_student'), ('is_admin', 'is_admin'), ('is_staff', 'is_staff')], default='0', max_length=20),
        ),
    ]
