# Generated by Django 3.2.6 on 2022-06-10 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220610_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(default=1234567890, max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
