# Generated by Django 3.2 on 2022-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220610_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('is_admin', 'is_admin'), ('is_staff', 'is_staff'), ('is_student', 'is_student')], default='0', max_length=20),
        ),
    ]
