# Generated by Django 3.2.5 on 2022-06-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('is_staff', 'is_staff'), ('is_admin', 'is_admin'), ('is_student', 'is_student')], default='0', max_length=20),
        ),
    ]
