# Generated by Django 3.2.5 on 2022-06-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('is_student', 'is_student'), ('is_admin', 'is_admin'), ('is_staff', 'is_staff')], default='0', max_length=20),
        ),
    ]
