# Generated by Django 3.2.6 on 2022-06-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_auto_20220613_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Comprehension', 'Comprehension'), ('Knowledge', 'Knowledge'), ('Application', 'Application')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.grade'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Fill_in_the_blanks', 'Fill_in_the_blanks'), ('MCQ', 'MCQ'), ('Match_the_following', 'Match_the_following')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.subject'),
        ),
    ]
